apiVersion: v1
kind: Service
metadata:
  name: mongoose-external
  namespace:
  labels:
spec:
  ports:
  - protocol: TCP 
    port: 5000
    targetPort: 5222
  selector:
    app: mongoose
  type: NodePort