apiVersion: v1
kind: Service
metadata:
  name: mongoose
  labels:
    app: mongoose
spec:
  ports:
  - name: one
    port: 4369
    targetPort: 4369
  - name: two
    port: 5222
    targetPort: 5222
  - name: three
    port: 5269
    targetPort: 5269
  - name: four
    port: 8500
    targetPort: 5280
  - name: five
    targetPort: 9100
    port: 9100
  clusterIP: None
  selector:
    app: mongoose
