apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-00
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/mnt/share-00"
    server: 10.10.10.2
  persistentVolumeReclaimPolicy: Recycle
