kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: keepalived
  namespace: kube-system
  labels:
    run: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      nodeSelector:
        keep: alive 
      hostNetwork: true
      containers:
      - name: init
        image: busybox:latest
        command:
          - sleep
          - "3600"
        envFrom:
        - configMapRef:
            name: keepalived
        volumeMounts:
        - name: config
          mountPath: /etc/keepalived
        - name: init
          mountPath: /etc/scripts
      volumes:
      - name: config
        emptyDir: {}
      - name: init
        configMap:
          name: keepalived-init
          defaultMode: 0700